(lang dune 3.20)

(name of)

(generate_opam_files true)

(source
 (github dponyatov/of))

(authors "Dmitry Ponyatov <dponyatov@gmail.com>")

(maintainers "Dmitry Ponyatov <dponyatov@gmail.com>")

(license MIT)

(documentation https://github.com/ponyatov/oF/wiki)

(package
 (name of)
 (synopsis "0F: zero FORTH in OCaml")
 (description "tiny REPL & compiler")
 (depends ocaml)
 (tags
  ("FORTH" "compiler" REPL demo)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
